version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '12:00'
    open-pull-requests-limit: 50
    versioning-strategy: 'increase'

  - package-ecosystem: 'npm'
    directory: '/api-service'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '12:00'
    open-pull-requests-limit: 50
    versioning-strategy: 'increase'

  - package-ecosystem: 'npm'
    directory: '/seeding-task'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '12:00'
    open-pull-requests-limit: 50
    versioning-strategy: 'increase'

  - package-ecosystem: 'npm'
    directory: '/website-static'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '12:00'
    ignore:
      - dependency-name: 'bootstrap'
        versions: ['>=5.0.0']
      - dependency-name: 'chart.js'
        versions: ['>=3.0.0']
    open-pull-requests-limit: 50
    versioning-strategy: 'increase'
