export const START_META_LOADING = "START_META_LOADING";
export const RECEIVE_META_DATA = "RECEIVE_META_DATA";
export const SET_META_ERROR = "SET_META_ERROR";
export const START_MOBILITY_LOADING = "START_MOBILITY_LOADING";
export const RECEIVE_MOBILITY_DATA = "RECEIVE_MOBILITY_DATA";
export const SET_MOBILITY_ERROR = "SET_MOBILITY_ERROR";